#!/usr/bin/env bash
# Configure nginx to run as the nginx user and listen on port 8080 of all IPs
useradd nginx 2>/dev/null
sed -i 's/^#*user .*/user nginx;/' /etc/nginx/nginx.conf
sed -i 's/listen 80\b/listen 8080/g' /etc/nginx/sites-enabled/default
sed -i 's/\]:80\b/]:8080/g' /etc/nginx/sites-enabled/default
service nginx restart
