#!/usr/bin/env bash
# Configures nginx with a custom X-Served-By response header set to the hostname

apt-get update -y
apt-get install -y nginx

echo "Holberton School" > /var/www/html/index.nginx-debian.html

sed -i "/server_name _;/a add_header X-Served-By \$hostname;" /etc/nginx/sites-available/default

service nginx restart
