#!/usr/bin/env bash
# Install and configure HAProxy on the load balancer with roundrobin
sudo apt-get update && sudo apt-get install haproxy -y
sudo sed -i 's/ENABLED=0/ENABLED=1/' /etc/default/haproxy

grep -q "frontend balancer_http_in" /etc/haproxy/haproxy.cfg ||
cat <<'CFG' | sudo tee -a /etc/haproxy/haproxy.cfg

frontend balancer_http_in
    bind *:80
    default_backend balancer_http_out

backend balancer_http_out
    balance roundrobin
    server 7131-web-01 54.82.205.51:80 check
    server 7131-web-02 18.234.101.46:80 check
CFG
sudo service haproxy restart
