#!/usr/bin/env bash
# Installs and configures nginx with a 301 redirect for /redirect_me

apt-get update -y
apt-get install -y nginx

echo "Holberton School" > /var/www/html/index.nginx-debian.html

sed -i '/server_name _;/a location /redirect_me { return 301 https://www.youtube.com/watch?v=QH2-TGUlwu4; }' /etc/nginx/sites-available/default

service nginx restart
