#!/usr/bin/env bash
# Installs and configures nginx with a custom 404 page

apt-get update -y
apt-get install -y nginx

echo "Holberton School" > /var/www/html/index.nginx-debian.html

sed -i '/server_name _;/a location /redirect_me { return 301 https://www.youtube.com/watch?v=QH2-TGUlwu4; }' /etc/nginx/sites-available/default

echo "Ceci n'est pas une page" > /var/www/html/404.html

sed -i '/server_name _;/a error_page 404 /404.html; location = /404.html { internal; }' /etc/nginx/sites-available/default

service nginx restart
